gardener/oidc-apps-controller

charts/oidc-apps-controller/templates/_helpers.tpl, charts/oidc-apps-controller/values.yaml
Fix a typo in the seed annotation key.
Also removes the gardener values and improves the documentation of the clients values. 
**Which issue(s) this PR fixes**:
Fixes #
**Special notes for your reviewer**:
**Release note**:
```feature user
```
=> Fix a typo in the seed annotation key

Makefile, pkg/constants/const.go, pkg/oidc-apps-controller/cmd.go, test/e2e/config/oidc-apps.yaml, test/e2e/crds/vpa-v1-crd-gen.yaml, test/e2e/deployment_test.go, test/e2e/setup.go, test/e2e/statefulset_test.go, test/e2e/suite_test.go
This PR brings controller-runtime webhook tests
* envtest.Environment contains WebhookInstallOptions with pod mutating webhook
* BeforeSuite contains logic for starting controller-runtime manager with webhook server
* "Oidc Apps Deployment Target Test" creates a target deployment, replicaset and a pod with proper owner references  
and validates the presence of the controller managed resources
* "Oidc Apps Statefulset Target Test" creates a target statefulset and a pod with proper owner references  
and validates the presence of the controller managed resources
-->
```feature developer
With controller-runtime envtests for the oidc-apps-controller mutating webhooks
```
=> Initial implementation of webhook controller-runtime env test

example/controller-registration.yaml, pkg/configuration/config.go, pkg/controllers/modifiers.go, pkg/controllers/oidc-apps-ingresses.go
This PR adds support for adding annotations to target ingresses.
Following example illustrates adding annotations to a grafana target, leveraging the default cert-manager and dns-manager extensions in gardener shoot clusters. Once the ingresses are annorated the respective extensions take over the lifecycle of the dns records and server-side certificates of the expose ingress.
```yaml
ingress:
create: true
ingressClassName: nginx
annotations:
cert.gardener.cloud/purpose: managed
dns.gardener.cloud/class: garden
dns.gardener.cloud/dnsnames: "*"
dns.gardener.cloud/ttl: "600"
nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
tlsSecretRef:
name: "grafana-tls"
```
```feature user
oidc-apps-controller now supports specifying annotations for the target ingresses
```
=> Support annotations in targets ingress resources

pkg/webhook/modifiers.go, pkg/webhook/oidc-check.sh
This PR migrates `oidc-init` container from classic init-container to sidecar container [k8s 1.29].
The purpose is to have a mechanism to ping upstream `oidc-provider` without interruption of the main application containers.
```other operator
The oidc-init will not interfere with start-up of the main application containers in the pod
```
=> Migrate "oidc-init" to sidecar container

pkg/webhook/modifiers.go, pkg/webhook/pod-webhook.go
This PR removes oidc-init container.
```other developer
oidc-init container is no longer added to the target pods
```
=> Remove oidc-init container

hack/.ci/component_descriptor
`.ci/component_descriptor` was copied into this repository from https://github.com/gardener/gardener.
Historically, the file used to be vendored into muliple repositories and thus needed to support
different repository-layouts. This is no longer the case, as vendoring was dropped some time back.
Rm unused codepath as cleanup (will help migrating from Concourse-Pipeline-Template).
**How to categorize this PR?**
/area delivery
/kind cleanup
**Release note**:
```other developer
drop unused codepath from component_descriptor creation script.
```
=> cleanup: drop unused codepath

imagevector/images.yaml
This PR updates container image dependencies:
- kube-rbac-proxy-watcher to v0.1.7
- oauth2-proxy to v7.8.1
```feature operator
Update sidecar containers oauth2-proxy to v7.8.1, kube-rbac-proxy-watcher to v0.1.7
```
=> Update upstream container dependencies

Dockerfile, go.mod
This PR updates go dependency to 1.23.5
```feature developer
Update go to v1.23.5
```
=> build: bump up golang to 1.23.5

example/provider-local/03-setup-controller.sh, example/provider-local/oidc-apps-controller-registration.yaml, pkg/webhook/modifiers.go
This PR sets unprivileged security context to controller and proxy containers. 
```feature developer
The controller container of "oidc-apps" and the managed proxy containers now run with an unprivileged security context.
```
=> Set unprivileged  security context

pkg/webhook/test/vpa-mutating-webhook_test.go, pkg/webhook/vpa-webhook.go
See https://github.com/gardener/gardener/pull/11366/files#r1953926916
**Which issue(s) this PR fixes**:
N/A
**Special notes for your reviewer**:
N/A
**Release note**:
```other operator
The `oauth2-proxy` and `kube-rbac-proxy` sidecars do no longer enable VPA as they do not benefit from it. Currently, VPA is only causing unnecessary evictions to the target StatefulSet/Deployment to apply resource recommendations for the  `oauth2-proxy` and `kube-rbac-proxy` sidecars.
```
=> Remove VPA for sidecar containers

imagevector/images.yaml
This PR brings the latest release of kube-rbac-proxy-watcher sidecar.
```feature user
None
```
=> Update kube-rbac-proxy-watcher to 0.1.8

.ci/pipeline_definitions
With this PR we start publishing the Helm charts in our OCI registry, that we can deploy it via `Extension` object.
**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/9635
**Special notes for your reviewer**:
**Release note**:
```feature operator
Helm charts of extension and admission controller are published as OCI artifacts now.
```
=> Publish helm chart to OCI registry

imagevector/images.yaml
This PR brings latest released version of kube-rbac-proxy-watcher sidecar.
```feature user
None
```
=> chore(deps): bump up kube-rbac-proxy-watcher to 0.1.9

.ci/pipeline_definitions
This PR updates `verify` image in CI pipeline to golang1.24.1
=> chore(ci): bump up verify image to golang:1.24.1

.github/workflows/unit-tests.yml
This PR simplifies the `unit-test` GitHub-action workflow.
- Removes unnecessary os matrix
- Uses go version from go.mod
=> chore(ci): simplify unit-test githubaction

.ci/pipeline_definitions
This PR updates CI verify image to golang:1.24.2.
=> Update ci verify image

Dockerfile, go.mod
This PR brings go 1.24.2 to `oidc-apps-controller`
```feature developer
Update `go` to 1.24.2
```
=> Update go to 1.24.2

imagevector/images.yaml
This PR brings updates to proxy sidecars.
- `oauth2-proxy` container is updated to [v7.8.2](https://github.com/oauth2-proxy/oauth2-proxy/releases/tag/v7.8.2)
- `kube-rbac-proxy-watcher` is updated to [v0.1.10](https://github.com/gardener/kube-rbac-proxy-watcher/releases/tag/v0.1.10)
```feat other developer
Proxy containers are updated:`oauth2-proxy` is updated to v7.8.2, `kube-rbac-proxy-watcher` is updated to v0.1.10
```
=> Update sidecars containers

.golangci.yaml, cmd/app/app.go, pkg/certificates/generate.go, pkg/certificates/generate_test.go, pkg/certificates/manager.go, pkg/certificates/operations.go, pkg/configuration/config.go, pkg/configuration/config_test.go, pkg/configuration/oauth2-proxy-template.go, pkg/configuration/resource-attributes-template.go, pkg/constants/const.go, pkg/controllers/image-pull-secret-reconciler.go, pkg/controllers/modifiers.go, pkg/controllers/namespace-reconciler.go, pkg/controllers/oidc-apps-ingresses.go, pkg/controllers/oidc-apps-secrets.go, pkg/controllers/oidc-apps-services.go, pkg/notifiers/gardener-access-token.go, pkg/oidc-apps-controller/cmd.go, pkg/oidc-apps-controller/options.go, pkg/rand/rand.go, pkg/webhook/modifiers.go, pkg/webhook/pod-webhook.go, pkg/webhook/test/pod-mutating-webhook_test.go, pkg/webhook/test/vpa-mutating-webhook_test.go, test/e2e/deployment_test.go, test/e2e/setup.go, test/e2e/statefulset_test.go, test/e2e/suite_test.go
This PR simplifies the project linter configuration by leveraging the default `revive` linter config.
The default configuration is available at [defaults.toml](https://github.com/mgechev/revive/blob/master/defaults.toml)
```other developer
Simpler linter configuration
```
=> Update linter configuration

.golangci.yaml
This PR brings a simpler linter configuration.
```other developer
None
```
=> Simple lint configuration

pkg/configuration/config.go, pkg/configuration/config_test.go, pkg/controllers/modifiers.go, pkg/controllers/oidc-apps-ingresses_test.go, pkg/webhook/pod-webhook.go, test/e2e/config/oidc-apps.yaml, test/e2e/deployment_test.go, test/e2e/setup.go, test/e2e/statefulset_test.go
This PR fixes ingress resource creation for the authentication sidecar.
Now the ingress resource is not created when is disabled in the target configuration.
For example with following target configuration
```
target:
- name:
ingress:
create: false
```
the `oidc-apps-controller` will not create an `Ingress` resource for the `oauth2-proxy` sidecar.
```feature user
```
=> Respect target configuration for creating ingress resources

imagevector/images.yaml
This PR brings oauth2-proxy version: v7.10.0, containing security fixes, dependencies updates and bug fixes.
- [oauth2-proxy v7.10.0 release notes](https://github.com/oauth2-proxy/oauth2-proxy/releases/tag/v7.10.0)
```operator dependency
oauth2-proxy v7.10.0 is the default the authentication container image in oidc-apps-controller
```
=> Update oauth2-proxy to v7.10.0

imagevector/images.yaml
**How to categorize this PR?**
/kind enhancement
/area oidc-apps
This PR updates the authentication and authorization proxy components by bumping the versions of two key images: `kube-rbac-proxy-watcher` from v0.1.12 to v0.1.13 and `oauth2-proxy` from v7.10.0 to v7.12.0. These updates ensure the OIDC apps extension uses the latest stable versions of these critical security components, bringing in potential bug fixes, security patches, and performance improvements.
**Code changes**:
- Updated `kube-rbac-proxy-watcher` image tag from `v0.1.12` to `v0.1.13`
- Updated `oauth2-proxy` image tag from `v7.10.0` to `v7.12.0`
- Changes made in `imagevector/images.yaml` configuration file
**Additional context**:
These are routine dependency updates for …
=> Update authentication and authorization proxies
